### ISSUE TITLE
Start in floating mode

### ISSUE THREAD

**Issue by cheginit** [regolith-linux/regolith-todo#2]
The `td-cli` window won't open in floating mode.

**Comment by cheginit** [comment]
I tried to use the script given [here](https://foxypanda.me/making-i3-windows-float-without-for-window/) but it doesn't work

**Comment by cheginit** [comment]
I came a little bit closer to a solution by adding:
```bash
for_window [title="tdi"] floating enable
```
to `i3/config` file but still cannot change the title of the terminal that runs `td-cli`.  I tried to follow the directions given [here](https://www.zachpfeffer.com/single-post/Change-the-title-of-a-terminal-on-Ubuntu-1604) for changing the title but it didn't work. This is the part of the blocklet that needs to be modified:
```bash
if [ -n "$button" ]; then
    /usr/bin/i3-msg -q exec "/usr/bin/x-terminal-emulator -e td --interactive"
fi
```

**Comment by kgilmer** [comment]
Just a guess, but perhaps better luck would come of indexing on WM_CLASS?  https://unix.stackexchange.com/questions/521019/specifying-the-wm-class-of-a-program

**Comment by cheginit** [comment]
@kgilmer The issue seems to be with using `/usr/bin/x-terminal-emulator`. It doesn't accept `--class` or `--name` options but if I use `gnome-terminal` directly it works.
