### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by Pasqat** [regolith-linux/regolith-todo#7]
If I try to install this repo I've this error

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-todo : Depends: td-cli but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I've installed td-cli with pip

**Comment by cheginit** [comment]
You don't need to install `td-cli` via `pip`. When you install `regolith-todo` it should automatically install `td-cli`. Which Regolith PPA are you using?

**Comment by Pasqat** [comment]
is this the information you need?

```shell
regolith-desktop:
  Installed: (none)
  Candidate: 2.124-1hirsute
  Version table:
     2.124-1hirsute 500
        500 http://ppa.launchpad.net/regolith-linux/release/ubuntu hirsute/main amd64 Packages
```

**Comment by Pasqat** [comment]
Sorry I'm not an expert, so I think the information you need are one of the following

```
regolith-compositor-picom-glx:
  Installed: 1.1.3-1
  Candidate: 1.1.3-1
  Version table:
 *** 1.1.3-1 500
        500 http://ppa.launchpad.net/regolith-linux/release/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
```
I've installed Regolith 1.6 Linux ISO

**Comment by cheginit** [comment]
So you're using the release PPA of Hirsute. By looking at the packages that are available for this [PPA](https://launchpad.net/~regolith-linux/+archive/ubuntu/release?field.series_filter=hirsute) `td-cli` is not available.

@kgilmer It seems that `td-cli` is not available for Hirsute at all. I looked at stable and unstable PPAs as well, and couldn't find it. Was there an issue with porting it for Hirsute or it's just missing?

**Comment by kgilmer** [comment]
Looks like a miss.  The script I use to sync across Ubuntu versions seems to be broken.  I've manually copied the package to Hirsute in the `release` PPA.   @Pasqat  please try again in a few hours after the package copy completes.

**Comment by Pasqat** [comment]
The installation goes well.
Know the problem is that if I click on che i3rocks icon on status bar nothings appen. If I try to add the keybinding to `i3/config` as show in the doc nothing appens.
I will try to figure this out.

Thank you
